// Mocks generated by Mockito 5.4.2 from annotations
// in web_os_control/test/web_os_button_controller.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:web_os/web_os_client_api/web_os_botton_api.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [WebOsButtonAPI].
///
/// See the documentation for Mockito's code generation for more information.
class MockWebOsButtonAPI extends _i1.Mock implements _i2.WebOsButtonAPI {
  @override
  _i3.Future<bool> pressedMediaPlayerKey(_i2.MediaPlayerKey? key) =>
      (super.noSuchMethod(
        Invocation.method(
          #pressedMediaPlayerKey,
          [key],
        ),
        returnValue: _i3.Future<bool>.value(false),
        returnValueForMissingStub: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
  @override
  _i3.Future<bool> pressedMotionKey(_i2.MotionKey? key) => (super.noSuchMethod(
        Invocation.method(
          #pressedMotionKey,
          [key],
        ),
        returnValue: _i3.Future<bool>.value(false),
        returnValueForMissingStub: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
  @override
  _i3.Future<bool> pressedWebOsTVApp(_i2.WebOsTvApp? app) =>
      (super.noSuchMethod(
        Invocation.method(
          #pressedWebOsTVApp,
          [app],
        ),
        returnValue: _i3.Future<bool>.value(false),
        returnValueForMissingStub: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
}
